### ISSUE TITLE
Is it possible to rewrite the UEFI BootLoader in C?

### ISSUE THREAD

**Issue by Hacker55541** [sven-eliasen/NotPetyaAgain#7]
Is it possible to rewrite the UEFI BootLoader in C?
And if yes then how so?

**Comment by sven-eliasen** [comment]
Of course, in fact this Rust UEFI bootloader use the same EFI ABI than the ones you write in C.

I would recommend you to start by looking at the EFI specifications.

As I told you one your other issue, I'm archiving this project so I'm closing this issue as well.
